---

- hosts: localhost
  tasks:
    - name: Install Chrome
      include_role:
        name: chrome

    - name: Install Java
      include_role:
        name: java

    - name: Install PyCharm
      include_role:
        name: pycharm

    - name: Install Tilix
      include_role:
        name: tilix

    - name: Install Slack
      include_role:
        name: slack

    - name: Set favorites
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: >
          "[
              'google-chrome.desktop',
              'firefox.desktop',
              'com.gexperts.Tilix.desktop',
              'org.gnome.Nautilus.desktop',
              'slack.desktop',
              'jetbrains-pycharm-ce.desktop'
           ]"
        state: present
