---

- hosts: localhost
  tasks:
    - name: Install common packages
      include_role:
        name: common

    - name: Install Java
      include_role:
        name: java

    - name: Install Bazel
      include_role:
        name: bazel

    - name: Install PyCharm
      include_role:
        name: pycharm

    - name: Set favorites
      dconf:
        key: /org/gnome/shell/favorite-apps
        value: >
          "[
              'google-chrome.desktop',
              'firefox.desktop',
              'com.gexperts.Tilix.desktop',
              'org.gnome.Nautilus.desktop',
              'slack.desktop',
              'jetbrains-pycharm-ce.desktop'
           ]"
        state: present
