---
# defaults file for common

common_apt_repos:
  - ppa:snwh/pulp
  - ppa:webupd8team/terminix

common_remove_apt_packages:
  - lightdm

common_apt_packages:
  # system
  - python-dev
  - gir1.2-gtop-2.0
  - gir1.2-networkmanager-1.0
  - gir1.2-clutter-1.0

  # gnome3
  - gnome-shell
  - gdm3
  - gnome-tweak-tool
  - paper-icon-theme
  - paper-cursor-theme
  - paper-gtk-theme

  # tools
  - silversearcher-ag
  - tilix
  - curl
  - htop
  - iotop
  - iftop

common_pip_packages:
  - psutil
  - virtualenvwrapper

common_slack_version: 2.9.0
common_slack_download_url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ common_slack_version }}-amd64.deb"

common_chrome_download_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

common_deb_packages:
  - "{{ common_slack_download_url }}"
  - "{{ common_chrome_download_url }}"
