---
# defaults file for bazel

bazel_download_mirror: https://github.com/bazelbuild/bazel/releases/download
bazel_version: 0.5.2
bazel_install_script: "bazel-{{ bazel_version }}-installer-linux-x86_64.sh"
bazel_download_url: "{{ bazel_download_mirror }}/{{ bazel_version }}/{{ bazel_install_script }}"

bazel_apt_dependencies:
  - pkg-config
  - zip
  - g++
  - zlib1g-dev
  - unzip
