---
# tasks file for common

- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
  become: yes
  with_items: "{{ common_apt_repos }}"

- name: Install apt packages
  apt:
    name: "{{ item }}"
  become: yes
  with_items: "{{ common_apt_packages }}"

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  become: yes
  with_items: "{{ common_deb_packages }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
    extra_args: --user
  with_items: "{{ common_pip_packages }}"

- name: Download fuzzy finder
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "~/.fzf"
    depth: 1

- name: Install fuzzy finder
  shell: "~/.fzf/install --all"

# move window controls to the right side (default is 'close,minimize,maximize:')
- name: Move window controls to the right side
  shell: "gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'"
